# Generated by Django 5.1.2 on 2024-11-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=30, unique=True)),
                ('rg', models.CharField(max_length=30, unique=True)),
                ('nis', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('grupoprioridade', models.CharField(blank=True, max_length=20, null=True)),
                ('registro', models.CharField(max_length=50)),
                ('encaminhamento', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('URLimagem', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=20)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estudante',
            },
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=10)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='meuapp.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='meuapp.professor')),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='meuapp.professor')),
            ],
            options={
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=30, unique=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='meuapp.estudante')),
            ],
            options={
                'db_table': 'responsavel',
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='meuapp.usuario'),
        ),
    ]
