# Generated by Django 5.1.2 on 2024-11-28 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='v_tela_classeEstudante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'v_tela_classeEstudante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V_tela_estudante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NOME', models.CharField(max_length=50)),
                ('EMAIL', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=30)),
                ('RESPONSAVEL', models.CharField(max_length=50)),
                ('TELEFONE', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'V_tela_estudante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dia', models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta')], max_length=7)),
            ],
            options={
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('URLimagem', models.URLField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('rua', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=20)),
                ('papel', models.CharField(choices=[('professor', 'Professor'), ('gerente', 'Gerente'), ('integracao', 'Integração'), ('emprego', 'Emprego')], max_length=20)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, max_length=10, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(db_column='idaula', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='meuapp.aula')),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=30, unique=True)),
                ('rg', models.CharField(max_length=30, unique=True)),
                ('nis', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('grupoprioridade', models.CharField(blank=True, max_length=20, null=True)),
                ('registro', models.CharField(max_length=50)),
                ('encaminhamento', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('URLimagem', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=20)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('idclasse', models.ForeignKey(blank=True, db_column='idclasse', null=True, on_delete=django.db.models.deletion.CASCADE, to='meuapp.classe')),
            ],
            options={
                'db_table': 'estudante',
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(db_column='idprofessor', on_delete=django.db.models.deletion.CASCADE, to='meuapp.professor'),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeResp', models.CharField(max_length=50)),
                ('telefoneResp', models.CharField(max_length=30)),
                ('idestudante', models.ForeignKey(db_column='idestudante', on_delete=django.db.models.deletion.CASCADE, to='meuapp.estudante')),
            ],
            options={
                'db_table': 'responsavel',
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='meuapp.usuario'),
        ),
    ]
