# Generated by Django 5.1.2 on 2024-11-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='idestudante',
            field=models.ManyToManyField(blank=True, related_name='classes', to='meuapp.estudante'),
        ),
    ]
