# Generated by Django 5.1.2 on 2024-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='observacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
