# Generated by Django 5.1.2 on 2024-11-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='idestudante',
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefoneResp',
            field=models.CharField(max_length=30),
        ),
    ]
